spring.application.name=library_lab2

# ???????????? ??????????? ?? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db_lab2
spring.datasource.username=postgres
spring.datasource.password=postgres

# ??????? ??? ?????? ? PostgreSQL (?? ???? ???????? ? Maven)
spring.datasource.driver-class-name=org.postgresql.Driver

# ???????????? JPA / Hibernate
# update ???????: "??????????? ???????? ??? ??????? ??????? ? ???? ?? ????? Java-???????"
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-?????? ? ??????? (???? ??????? ??? ?????????, ?? ?????? Hibernate)
spring.jpa.show-sql=true

# ??????? ??? ?????????? ????????? ??????? ???? ??? PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect